name: bro_form_validator
description: Form validator that provide common and custom validators for brovelopers
version: 0.1.1
homepage: https://github.com/SamuelMauricioL/bro_form_validator
topics: [form, validator]

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
